services:
  - type: web
    name: taskgo-server
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true

