services:
  - type: web
    name: taskgo-server
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: server/app-server/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: DB_ENABLE
        value: true
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false

